version: '3'
services:
  web:
    build: .
    ports:
      - '8080:8080'
    command: node_modules/.bin/nodemon --exec npm start
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - .:/home/app/rotas
      - /home/app/rotas/node_modules
    tty: true
  mysql:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
