version: '3'
services:
  web:
    build: .
    ports:
      - '8080:8080'
    command: node_modules/.bin/nodemon -L --exec npm start
    links:
      - mysql
      - translator
    depends_on:
      - mysql
      - translator
    volumes:
      - .:/home/app/rotas
      - /home/app/rotas/node_modules
    tty: true
  mysql:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
    volumes:
      - db-data:/var/lib/mysql
  translator:
    image: julinho/tradutor
    expose:
      - 3000
    environment:
      MQTT_BROKER: mqtt.sj.ifsc.edu.br
      ROBOT: julinho
volumes:
  db-data:
