version: '3'
services:
  web:
    build: .
    ports:
      - '8080:8080'
    command: node_modules/.bin/nodemon -L --exec npm start
    links:
      - mysql
      - translator
      - mongo
    depends_on:
      - mysql
      - translator
      - mongo
    volumes:
      - .:/home/app/rotas
    tty: true
  mysql:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
    volumes:
      - db-data:/var/lib/mysql
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
  translator:
    image: julinho/tradutor
    expose:
      - 3000
    environment:
      MQTT_BROKER: mqtt.sj.ifsc.edu.br
      ROBOT: julinho
volumes:
  db-data:
  mongo-data:
