version: '3'
services:
  web:
    build: .
    ports:
      - '8080:8080'
    links:
      - mysql
      - julinho_translator
      - julinha_translator
      - mongo
    depends_on:
      - mysql
      - julinho_translator
      - julinha_translator
      - mongo
  mysql:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
    volumes:
      - db-data:/var/lib/mysql
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
  julinho_translator:
    image: julinho/tradutor:latest
    expose:
      - 3000
    environment:
      MQTT_BROKER: nuvem2.sj.ifsc.edu.br
      ROBOT: julinho
  julinha_translator:
    image: julinho/tradutor:latest
    expose:
      - 3000
    environment:
      MQTT_BROKER: nuvem2.sj.ifsc.edu.br
      ROBOT: julinha
volumes:
  db-data:
  mongo-data:
