version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - mysql
    volumes:
      - .:/app
  mysql:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
